<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="User-ПК" name="ru.ct.tests.ListTest" tests="13" failures="1" timestamp="9 Dec 2015 07:09:25 GMT" time="850.041" errors="1">
  <testcase name="positiveRegistrationTests" time="4.676" classname="ru.ct.tests.ListTest"/>
  <testcase name="negativeRegistrationTests" time="9.065" classname="ru.ct.tests.ListTest"/>
  <testcase name="find500ErrorsOnPagesTest" time="124.196" classname="ru.ct.tests.ListTest"/>
  <testcase name="positiveRegistrationTests" time="4.347" classname="ru.ct.tests.ListTest">
    <failure type="java.lang.AssertionError" message="Не произошло перехода на страницу подтверждения регистрации по СМС/ПОЧТЕ
User [idAccount=0, name=$a-=G)кWиыПБC0-ЕV7)т#dЧ8с^Ds*3+!t3e@@G9ь10lw4В&amp;У&amp;J5д_Ч^БgTьъ%&amp;ЖpcbЭABН0$3ZdЁ8bб4Ф&amp;жpв9*)еe4b7V82IaBD7pu2Я6WциЬЕб!Эр)3uw1ё=7ыЛ%ЯU7_OoдхД9FбSH$яИ@У2LЭ@R-fЖq##, phoneMob=7123088870, email=NtCnJdJtVsk@cutHsjAMSDUdZ.eu, site=мтъЁБмжеМВжЛФФЫв.рф, loginName=null, psw=null, type=null, sites=null, startDate=null, endDate=null]">
      <![CDATA[java.lang.AssertionError: Не произошло перехода на страницу подтверждения регистрации по СМС/ПОЧТЕ
User [idAccount=0, name=$a-=G)кWиыПБC0-ЕV7)т#dЧ8с^Ds*3+!t3e@@G9ь10lw4В&У&J5д_Ч^БgTьъ%&ЖpcbЭABН0$3ZdЁ8bб4Ф&жpв9*)еe4b7V82IaBD7pu2Я6WциЬЕб!Эр)3uw1ё=7ыЛ%ЯU7_OoдхД9FбSH$яИ@У2LЭ@R-fЖq##, phoneMob=7123088870, email=NtCnJdJtVsk@cutHsjAMSDUdZ.eu, site=мтъЁБмжеМВжЛФФЫв.рф, loginName=null, psw=null, type=null, sites=null, startDate=null, endDate=null]
	at ru.ct.helpers.AutorithationHelper.verifyThatImOnConfirmedPage(AutorithationHelper.java:278)
	at ru.ct.helpers.AutorithationHelper.positiveRegistrationTest(AutorithationHelper.java:30)
	at ru.ct.tests.ListTest.positiveRegistrationTests(ListTest.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
    </failure>
  </testcase> <!-- positiveRegistrationTests -->
  <testcase name="negativeRegistrationTests" time="2.995" classname="ru.ct.tests.ListTest"/>
  <testcase name="negativeRegistrationTests" time="2.953" classname="ru.ct.tests.ListTest"/>
  <testcase name="negativeRegistrationTests" time="18.744" classname="ru.ct.tests.ListTest"/>
  <testcase name="negativeRegistrationTests" time="2.854" classname="ru.ct.tests.ListTest"/>
  <testcase name="positiveRegistrationTests" time="4.518" classname="ru.ct.tests.ListTest"/>
  <testcase name="positiveRegistrationTests" time="4.801" classname="ru.ct.tests.ListTest"/>
  <testcase name="testAuthGenerator" time="0.000" classname="ru.ct.tests.ListTest">
    <error type="java.lang.RuntimeException" message="java.io.IOException: Stream closed">
      <![CDATA[java.lang.RuntimeException: java.io.IOException: Stream closed
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:162)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:430)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1270)
	at org.testng.internal.Invoker.createParameters(Invoker.java:985)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1075)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
Caused by: java.io.IOException: Stream closed
	at java.io.BufferedReader.ensureOpen(Unknown Source)
	at java.io.BufferedReader.readLine(Unknown Source)
	at java.io.BufferedReader.readLine(Unknown Source)
	at ru.ct.dp.DataGeneratorAuth.loadAuthHelperFromFile(DataGeneratorAuth.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:154)
	... 20 more
]]>
    </error>
  </testcase> <!-- testAuthGenerator -->
  <testcase name="positiveRegistrationTests" time="5.752" classname="ru.ct.tests.ListTest"/>
  <testcase name="find500ErrorsOnPagesTest" time="665.140" classname="ru.ct.tests.ListTest"/>
</testsuite> <!-- ru.ct.tests.ListTest -->
